export const ACTION_TEST = 'ACTION_TEST';
export const ACTION_SELECT_CLIENT = 'ACTION_SELECT_CLIENT';
export const ACTION_GET_CLIENTS = 'ACTION_GET_CLIENTS';
export const ACTION_SEARCH_CLIENTS = 'ACTION_SEARCH_CLIENTS';
